# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [86]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [87]:
# Create a 1-dimensional NumPy array using np.array()
arr_1d = np.array([1, 2, 3, 4])

# Create a 2-dimensional NumPy array using np.array()
arr_2d = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8]])

# Create a 3-dimensional Numpy array using np.array()
arr_3d = np.array(
         [
             [[1, 2, 3], [3, 4, 5]],
             [[5, 6, 7], [7, 8, 9]]
         ]
        )

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [88]:
# Attributes of 1-dimensional array (shape,
# number of dimensions, data type, size and type)
print(f"shape = {arr_1d.shape}")
print(f"number of dimensions = {arr_1d.ndim}")
print(f"data type = {arr_1d.dtype}")
print(f"size = {arr_1d.size}")
print(f"type = {type(arr_1d)}")

shape = (4,)
number of dimensions = 1
data type = int64
size = 4
type = <class 'numpy.ndarray'>


In [89]:
# Attributes of 2-dimensional array
print(f"shape = {arr_2d.shape}")
print(f"number of dimensions = {arr_2d.ndim}")
print(f"data type = {arr_2d.dtype}")
print(f"size = {arr_2d.size}")
print(f"type = {type(arr_2d)}")

shape = (2, 4)
number of dimensions = 2
data type = int64
size = 8
type = <class 'numpy.ndarray'>


In [90]:
# Attributes of 3-dimensional array
print(f"shape = {arr_3d.shape}")
print(f"number of dimensions = {arr_3d.ndim}")
print(f"data type = {arr_3d.dtype}")
print(f"size = {arr_3d.size}")
print(f"type = {type(arr_3d)}")

shape = (2, 2, 3)
number of dimensions = 3
data type = int64
size = 12
type = <class 'numpy.ndarray'>


In [91]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd

# Creating dataframe form 2D-array
df = pd.DataFrame(arr_2d)

# Printing dataframe
df

0  1  2  3
0  1  2  3  4
1  5  6  7  8

In [92]:
# Create an array of shape (10, 2) with only ones
ones_arr = np.ones((10, 2), dtype=np.int8)

print(ones_arr)

[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]


In [93]:
# Create an array of shape (7, 2, 3) of only zeros

zeros_arr = np.zeros((7, 2, 3), dtype=np.int8)

print(zeros_arr)

[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]


In [94]:
# Create an array within a range of 0 and 100 with step 3
np.arange(0, 100, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [95]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
np.random.randint(10, size=(7, 2))

array([[4, 0],
       [2, 9],
       [7, 5],
       [7, 8],
       [3, 0],
       [0, 9],
       [3, 6]])

In [96]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
np.random.rand(3, 5)

array([[0.49724851, 0.30087831, 0.28484049, 0.03688695, 0.60956433],
       [0.50267902, 0.05147875, 0.27864646, 0.90826589, 0.23956189],
       [0.14489487, 0.48945276, 0.98565045, 0.24205527, 0.67213555]])

In [97]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
np.random.randint(10, size=(4, 6))

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

    the elements of the array didn't change.
Are the numbers in the array different or the same? Why do think this is?

    the same, seed function saves the state of the random function.

In [98]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
rndarr = np.random.randint(1, 10, size=(3, 7))

# Find the unique numbers in the array you just created
np.unique(rndarr)

array([1, 2, 3, 4, 5, 7, 9])

In [99]:
# Find the 0'th index of the latest array you created
rndarr[0]

array([9, 1, 3, 7, 4, 9, 3])

In [100]:
# Get the first 2 rows of latest array you created
rndarr[0:2]

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]])

In [101]:
# Get the first 2 values of the first 2 rows of the latest array
rndarr[0:2, 0:2]

array([[9, 1],
       [5, 3]])

In [102]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
random_array = np.random.randint(10, size=(3, 5))

print(random_array)

array_ones_1 = np.ones((3, 5), dtype=np.int8)

[[6 7 2 0 3]
 [1 7 3 1 5]
 [5 9 3 5 1]]


In [103]:
# Add the two arrays together
random_array + array_ones_1

array([[ 7,  8,  3,  1,  4],
       [ 2,  8,  4,  2,  6],
       [ 6, 10,  4,  6,  2]])

In [104]:
# Create another array of ones of shape (5, 3)
array_ones_2 = np.ones((5, 3), dtype=np.int8)

In [105]:
# Try add the array of ones and the other most recent array together
random_array + array_ones_2

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?

the sizes were different.

How would you fix it?

change the size of the second array of ones or may be reshaping 'random array'

In [106]:
# Create another array of ones of shape (3, 5)
array_ones_3 = np.ones((3, 5), dtype=np.int8)
array_ones_3

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

In [107]:
# Subtract the new array of ones from the other most recent array
random_array - array_ones_3

array([[ 5,  6,  1, -1,  2],
       [ 0,  6,  2,  0,  4],
       [ 4,  8,  2,  4,  0]])

In [108]:
# Multiply the ones array with the latest array
array_ones_3 * random_array

array([[6, 7, 2, 0, 3],
       [1, 7, 3, 1, 5],
       [5, 9, 3, 5, 1]])

In [109]:
# Take the latest array to the power of 2 using '**'
print(random_array)
random_array ** 2

[[6 7 2 0 3]
 [1 7 3 1 5]
 [5 9 3 5 1]]


array([[36, 49,  4,  0,  9],
       [ 1, 49,  9,  1, 25],
       [25, 81,  9, 25,  1]])

In [110]:
# Do the same thing with np.square()
np.square(random_array)

array([[36, 49,  4,  0,  9],
       [ 1, 49,  9,  1, 25],
       [25, 81,  9, 25,  1]])

In [111]:
# Find the mean of the latest array using np.mean()
np.mean(random_array)

3.8666666666666667

In [112]:
# Find the maximum of the latest array using np.max()
np.max(random_array)

9

In [113]:
# Find the minimum of the latest array using np.min()
np.min(random_array)

0

In [114]:
# Find the standard deviation of the latest array
np.std(random_array)

2.578543947441829

In [115]:
# Find the variance of the latest array
# Variance is the square root of the standard deviation
np.square(np.std(random_array))

6.648888888888889

In [116]:
# Reshape the latest array to (3, 5, 1)
print(random_array)

random_array.reshape(3, 5, 1)

[[6 7 2 0 3]
 [1 7 3 1 5]
 [5 9 3 5 1]]


array([[[6],
        [7],
        [2],
        [0],
        [3]],

       [[1],
        [7],
        [3],
        [1],
        [5]],

       [[5],
        [9],
        [3],
        [5],
        [1]]])

In [117]:
# Transpose the latest array
print(random_array)

random_array.transpose()


[[6 7 2 0 3]
 [1 7 3 1 5]
 [5 9 3 5 1]]


array([[6, 1, 5],
       [7, 7, 9],
       [2, 3, 3],
       [0, 1, 5],
       [3, 5, 1]])

What does the transpose do?

change the axes.

In [120]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
random_array_2 = np.random.randint(10, size=(3, 3))
random_array_3 = np.random.randint(10, size=(3, 2))

print(random_array_2)
print(random_array_3)

[[8 7 0]
 [7 7 2]
 [0 7 2]]
[[2 0]
 [4 9]
 [6 9]]


In [121]:
# Perform a dot product on the two newest arrays you created
np.dot(random_array_2, random_array_3)

array([[44, 63],
       [54, 81],
       [40, 81]])

In [125]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
random_array_4 = np.random.randint(10, size=(4, 3))
random_array_5 = np.random.randint(10, size=(4, 3))

print(random_array_4)
print(random_array_5)

[[9 6 8]
 [6 0 0]
 [8 8 3]
 [8 2 6]]
[[5 7 8]
 [4 0 2]
 [9 7 5]
 [7 8 3]]


In [126]:
# Perform a dot product on the two newest arrays you created
np.dot(random_array_4, random_array_5)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [130]:
# Take the latest two arrays, perform a transpose on one of them and then perform
# a dot product on them both
random_array_4 = random_array_4.transpose()
np.dot(random_array_4, random_array_5)

array([[197, 183, 148],
       [116, 114,  94],
       [109, 125,  97]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [131]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
random_array_6 = np.random.randint(10, size=(3, 3))
random_array_7 = np.random.randint(10, size=(3, 3))

print(random_array_6)
print(random_array_7)

[[0 0 9]
 [3 6 1]
 [2 0 4]]
[[0 7 0]
 [0 1 1]
 [5 6 4]]


In [134]:
# Compare the two arrays with '>'
random_array_6 > random_array_7

array([[False, False,  True],
       [ True,  True, False],
       [False, False, False]])

What happens when you compare the arrays with `>`?

In [135]:
# Compare the two arrays with '>='
random_array_6 >= random_array_7

array([[ True, False,  True],
       [ True,  True,  True],
       [False, False,  True]])

In [136]:
# Find which elements of the first array are greater than 7
random_array_6 > 7

array([[False, False,  True],
       [False, False, False],
       [False, False, False]])

In [137]:
# Which parts of each array are equal? (try using '==')
random_array_6 == random_array_7

array([[ True, False, False],
       [False, False,  True],
       [False, False,  True]])

In [138]:
# Sort one of the arrays you just created in ascending order
print(random_array_6)
print('\n')
np.sort(random_array_6)

[[0 0 9]
 [3 6 1]
 [2 0 4]]




array([[0, 0, 9],
       [1, 3, 6],
       [0, 2, 4]])

In [140]:
# Sort the indexes of one of the arrays you just created
print(random_array_7)
np.argsort(random_array_7)

[[0 7 0]
 [0 1 1]
 [5 6 4]]


array([[0, 2, 1],
       [0, 1, 2],
       [2, 0, 1]])

In [141]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(random_array_7)

1

In [142]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(random_array_7)

0

In [143]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(random_array_7, 1)

array([1, 1, 1])

In [144]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(random_array_7, 0)

array([0, 1, 0])

In [145]:
# Create an array of normally distributed random numbers
np.random.normal(2, 3, (3, 2))

array([[ 5.71104822, -2.27943665],
       [ 3.01406798,  7.92371359],
       [ 7.89510429, -3.81973366]])

In [146]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1, 100, 10, dtype=np.int8)

array([  1,  12,  23,  34,  45,  56,  67,  78,  89, 100], dtype=int8)

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.